apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  kafka-setup-k8s.sh: |
    #!/bin/bash
    # Wait for Kafka to be ready
    echo "Waiting for Kafka to be ready..."
    for i in {1..30}; do
      if /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list > /dev/null 2>&1; then
        echo "Kafka is ready!"
        break
      fi
      echo "Waiting for Kafka..."
      sleep 2
    done
    # Create topics
    /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic raw-financial-data --partitions 3 --replication-factor 1
    /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic transformed-financial-data --partitions 3 --replication-factor 1
    echo "Kafka topics created successfully!"