apiVersion: v1
kind: PersistentVolume
metadata:
name: cassandra-pv
spec:
capacity:
storage: 5Gi
accessModes:
- ReadWriteOnce
persistentVolumeReclaimPolicy: Retain
storageClassName: hostpath
hostPath:
path: /home/abelc/data/cassandra
type: DirectoryOrCreate