apiVersion: v1
kind: PersistentVolume
metadata:
name: zookeeper-pv
spec:
capacity:
storage: 1Gi
accessModes:
- ReadWriteOnce
persistentVolumeReclaimPolicy: Retain
storageClassName: hostpath
hostPath:
path: /tmp/zookeeper-data
type: DirectoryOrCreate